Created CHIMERA and related simulation data
R3BRootGroup/asyeos pull request #9
Opened 2023-03-16 17:00 UTC by edefilippo

Created CHIMERA and related simulation data, first version compatible with R3BRoot/dev

2023-03-16 17:46 UTC, jose-luis-rs requested changes
Please, don't forget to add the new folders
-asydata
-chimera
to the main CMakeLists.txt file:
https://github.com/R3BRootGroup/asyeos/blob/dev/CMakeLists.txt

2023-03-16 17:46 UTC, jose-luis-rs commented on asydata/CMakeLists.txt
> +# Create a library called "libR3BasyData" which includes the source files given in
the name of this lib should be "libR3B**A**syData"

2023-03-16 17:46 UTC, jose-luis-rs commented on asydata/CMakeLists.txt
> +set(LINKDEF  R3BasyDataLinkDef.h)
R3B**A**syDataLinkDef.h

2023-03-16 17:46 UTC, jose-luis-rs commented on asydata/CMakeLists.txt
> +set(LIBRARY_NAME R3BasyData)
R3B**A**syData

2023-03-16 17:46 UTC, jose-luis-rs commented on asydata/R3BasyDataLinkDef.h
> +// 2017/04/07 12:02:26 hapol
this file is excluded from the clang-format, for this you must add this line:
// clang-format off

2023-03-16 17:46 UTC, jose-luis-rs commented on asydata/R3BasyDataLinkDef.h
> +#pragma link C++ class R3BAsyChimeraPoint + ;
without space:
#pragma link C++ class R3BAsyChimeraPoin**t+;**

2023-03-16 17:46 UTC, jose-luis-rs commented on asydata/chimeraData/R3BAsyChimeraHitData.h
> +    inline const Int_t& GetDetId() const { return fDetId; }
With this line is enough:
Int_t GetDetId() const { return fDetId; }
remove the **inline const**

2023-03-16 17:46 UTC, jose-luis-rs commented on asydata/chimeraData/R3BAsyChimeraHitData.h
> +    inline const Int_t& GetDetId() const { return fDetId; }
in general

2023-03-16 17:46 UTC, jose-luis-rs commented on asydata/chimeraData/R3BAsyChimeraPoint.cxx
> +void R3BAsyChimeraPoint::Print(const Option_t* opt) const
The print function is not used anymore, please, remove it. See for instance:
https://github.com/R3BRootGroup/R3BRoot/blob/dev/r3bdata/alpideData/R3BAlpidePoint.cxx
https://github.com/R3BRootGroup/R3BRoot/blob/dev/r3bdata/alpideData/R3BAlpidePoint.h

2023-03-16 17:46 UTC, jose-luis-rs commented on chimera/AsyChimLinkDef.h
> +#ifdef __CINT__
Please, add:
// clang-format off

2023-03-16 17:46 UTC, jose-luis-rs commented on chimera/AsyChimLinkDef.h
> +#pragma link C++ class R3BAsyChimera + ;
without spaces: ...Chimera + ; ---> ...Chimera+;

2023-03-16 17:46 UTC, jose-luis-rs commented on chimera/CMakeLists.txt
> +# Create a library called "libasySofChim" which includes the source files given in
should be "libR3BAsyChim"

2023-03-16 17:46 UTC, jose-luis-rs commented on chimera/R3BAsyChimera.cxx
> +            // Cal Data for each plastic
Please, remove the commented code!

2023-03-16 17:46 UTC, jose-luis-rs commented on chimera/R3BAsyChimera.cxx
> +            // Cal Data for each plastic
Please, update this class according to:
https://github.com/R3BRootGroup/sofia/blob/dev/tofwall/sim/R3BSofTofW.cxx

2023-03-16 17:46 UTC, jose-luis-rs commented on chimera/R3BAsyChimeraContFact.cxx
> +
Please, update this class according to:
https://github.com/R3BRootGroup/R3BRoot/blob/dev/twim/pars/R3BTwimContFact.cxx
https://github.com/R3BRootGroup/R3BRoot/blob/dev/twim/pars/R3BTwimContFact.h

2023-03-20 13:58 UTC, closed without merging

2023-03-20 13:59 UTC, edefilippo commented
Closed after doing all requested changes. We open a new one just after